repos:
  - repo: local
    hooks:
      - id: freeze-requirements
        name: Auto Freeze Requirements
        entry: bash backend/scripts/freeze_requirements.sh
        language: system
        files: ^.*\.py$
