version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/dev.dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=project.settings.dev
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - db
    networks:
      - backend_network
  
  frontend:
    build:
      context: .
      dockerfile: frontend/dev.dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - backend_network

  # PostgreSQL Database
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: django_react_db
      POSTGRES_USER: django_react_user
      POSTGRES_PASSWORD: django_react_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_network
    ports:
      - "5432:5432"

volumes:
  postgres_data:

networks:
  backend_network:
    driver: bridge
