version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/prod.dockerfile
    environment:
      - DJANGO_SETTINGS_MODULE=project.settings.prod
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - SECRET_KEY=${SECRET_KEY}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - backend_network
    command: ["gunicorn", "--bind", "0.0.0.0:8000", "project.wsgi:application"]

  frontend:
    build:
      context: .
      dockerfile: frontend/prod.dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - backend_network

  db:
    image: postgres:15
    environment:
      POSTGRES_DB=${POSTGRES_DB}
      POSTGRES_USER=${POSTGRES_USER}
      POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_network
    ports:
      - "5432:5432"

volumes:
  postgres_data:

networks:
  backend_network:
    driver: bridge
